# Generated by Django 4.0.4 on 2022-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cost_per_hour',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=15, verbose_name='Стоимость часа'),
        ),
    ]
