# Generated by Django 3.2.9 on 2021-11-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Брэнд')),
                ('full_loading', models.BooleanField(default=False, verbose_name='Загружено полностью')),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Комплектация')),
                ('full_loading', models.BooleanField(default=False, verbose_name='Загружено полностью')),
            ],
            options={
                'verbose_name': 'Комплектация',
                'verbose_name_plural': 'Комплектации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('full_loading', models.BooleanField(default=False, verbose_name='Загружено полностью')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autonorms.brand')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Модификация')),
                ('year', models.CharField(max_length=50, verbose_name='Год')),
                ('horsepower', models.FloatField(verbose_name='Мощность, л.с.')),
                ('engine_power', models.FloatField(verbose_name='Мощность, кВт')),
                ('engine_code', models.CharField(max_length=50, verbose_name='Код двигателя')),
                ('engine_volume', models.FloatField(verbose_name='Объем, см³')),
                ('car_body', models.CharField(max_length=100, verbose_name='Кузов')),
                ('full_loading', models.BooleanField(default=False, verbose_name='Загружено полностью')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autonorms.model')),
            ],
            options={
                'verbose_name': 'Модификация',
                'verbose_name_plural': 'Модификации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Узел')),
            ],
            options={
                'verbose_name': 'Узел',
                'verbose_name_plural': 'Узлы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Группа работ')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autonorms.equipment')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autonorms.model')),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autonorms.modification')),
            ],
            options={
                'verbose_name': 'Группа работ',
                'verbose_name_plural': 'Группы работ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Работа')),
                ('work_number', models.CharField(max_length=20, verbose_name='Каталожный номер')),
                ('working_hour', models.FloatField(verbose_name='Норма времени')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('vehicle_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autonorms.vehicleunit')),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autonorms.workgroup')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.AddField(
            model_name='vehicleunit',
            name='workgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autonorms.workgroup'),
        ),
        migrations.CreateModel(
            name='SubWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Составная работа')),
                ('work_number', models.CharField(max_length=20, verbose_name='Каталожный номер')),
                ('working_hour', models.FloatField(verbose_name='Норма времени')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('optional', models.BooleanField(default=False, verbose_name='Опциональная')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autonorms.work')),
            ],
            options={
                'verbose_name': 'Составная работа',
                'verbose_name_plural': 'Составные работы',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('part_number', models.CharField(max_length=25, verbose_name='Артикул')),
                ('work_number', models.CharField(max_length=20, verbose_name='Каталожный номер работы')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autonorms.model')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autonorms.modification'),
        ),
    ]
